### PR TITLE
XUnitFormatter fixes for issues #176, #177 and #178

### PR DESCRIPTION
**Pull request by BennieCopeland**

### CODE REVIEW

**Comment by BennieCopeland** [comment]
I haven't been able to build it or test because I'm already on VS2017. I don't want to go upgrading your projects.

**Comment by BrainCrumbz** [comment]
Thanks for this PR, will have a look at it. Yes, this is still VS2015-, project.json-based and it will probably stay like that for now (integrating with VS2017, of course, is another thing).

**Comment by BrainCrumbz** [comment]
Heads up: putting together a couple of tests for issues you found, to also confirm fixes.

**Comment by BrainCrumbz** [comment]
Collectively, this PR should fix issues #176, #177 and #178

**Pull request merged**
